FROM python:3.10

WORKDIR /root/Work_space

RUN apt-get update && apt-get install curl git -y

RUN apt-get install pipenv -y

RUN curl -sSL https://install.python-poetry.org | python3 -

ENV POETRY_HOME="/root/.local"

ENV PATH="$POETRY_HOME/bin:$PATH"

RUN /root/.local/bin/poetry config virtualenvs.create false

RUN python3 -m pip install bpython

CMD [ "python3" ]

# docker run -it -v $(pwd):/root/Work_space --name py_env vigneshr94/python_env:latest
