FROM python:3.11-alpine

WORKDIR /root/Work_space

RUN apk update && apk add gcc libc-dev make libffi-dev curl git bash

RUN curl -sSL https://install.python-poetry.org | python3 -

ENV POETRY_HOME="/root/.local"

ENV PATH="$POETRY_HOME/bin:$PATH"

RUN /root/.local/bin/poetry config virtualenvs.create false

ENTRYPOINT [ "/bin/bash" ]