FROM python:3.11-alpine

WORKDIR /root/Work_space

RUN apk update && apk add bash curl make gcc libc-dev libffi-dev git vim

RUN curl -sSL https://install.python-poetry.org | python3 -

ENV POETRY_HOME="/root/.local"

ENV PATH="$POETRY_HOME/bin:$PATH"

RUN /root/.local/bin/poetry config virtualenvs.create false

RUN python3 -m pip install bpython

ENTRYPOINT [ "/bin/bash" ]

# docker run -it -v $(pwd):/root/Work_space --name py_env vigneshr94/python_env:latest

