import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

live_config_reload = true
[env]
term = "screen-256colors"

[font]
normal = { family="FiraCode Nerd Font Mono", style="Regular" }
bold = { family="FiraCode Nerd Font Mono", style="Bold" }
italic = { family="FiraCode Nerd Font Mono", style="Italic" }
bold_italic = { family="FiraCode Nerd Font Mono", style="Bold Italic" }
size = 15.0

[window]
padding = {x=5, y=5}
dynamic_padding = true
decorations = "Buttonless"
startup_mode = "Maximized"
opacity = 1
blur = true
dynamic_title = true

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "Always" }
vi_mode_style = { shape = "Block", blinking = "Off" }
blink_interval = 500
blink_timeout = 0
